server:
    port: 11100
spring:
    h2:
        console:
            enabled: true # /h2-console
            settings.web-allow-others: true
    datasource:
        driver-class-name: org.h2.Driver
        username: joseluzon
        password:
        url: jdbc:h2:mem:udemy-springframework5_db