version: '3.8'

services:
  devenv-java:
    image: joseluzon/amazon-corretto_jdk17
    container_name: dev-java
    tty: true
    ports:
      - 11100:11100
    networks:
      - devenv_network
    volumes:
      - devenv-java-workspace:/workspace/
      - devenv-m2:/root/.m2
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  prometheus:
    image: prom/prometheus:v2.37.6 # LTS
    container_name: prometheus
    ports:
      - 12100:9090
    networks:
      - devenv_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256G
  
  grafana:
    image: grafana/grafana-oss:9.4.7
    container_name: grafana
    ports:
      - 13100:3000
    networks:
      - devenv_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256G
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 14100:6379
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - devenv_network
    volumes:
      - devenv-redis:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-1
    networks:
      - devenv_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    depends_on:
      - zookeeper-1
    networks:
      - devenv_network
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/log4j.properties.template
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  devenv_network:
    driver: bridge

volumes:
  devenv-java-workspace:
  devenv-m2:
